#include "teste.h"

int         teste_falhas = 0;
int         teste_total  = 0;
const char *teste_nome   = "";
bool        teste_quebrou = false;

void t_xadrez_posicao_inicial(void);
void t_xadrez_peao_anda_sem_saltar(void);
void t_xadrez_lance_troca_o_turno(void);
void t_xadrez_en_passant(void);
void t_xadrez_roque_move_rei_e_torre(void);
void t_xadrez_promocao_oferece_quatro_pecas(void);
void t_xadrez_reconhece_mate_e_empates(void);
void t_xadrez_navega_so_por_candidatos_validos(void);
void t_xadrez_maquina_e_legal_deterministica_e_fatiada(void);
void t_xadrez_maquina_media_aproveita_captura_livre(void);
void t_xadrez_maquina_facil_nao_desfaz_o_ultimo_lance(void);
void t_xadrez_salva_e_retoma_lance(void);
void t_xadrez_recusa_salvamento_corrompido(void);
void t_xadrez_pasta_ausente_e_partida_ausente(void);
void t_xadrez_historico_vem_recente_e_opcoes_nao_duplicam_lance(void);
void t_xadrez_da_home_ao_primeiro_lance_local(void);
void t_xadrez_saida_preserva_ou_abandona_partida(void);
void t_xadrez_salvamento_corrompido_tem_saida_segura(void);
void t_xadrez_back_limpa_ao_trocar_tabuleiro_e_saida(void);
void t_xadrez_back_segurado_volta_para_home(void);
void t_xadrez_maquina_responde_e_salva_sem_bloquear_back(void);
void t_xadrez_maquina_com_pretas_da_pessoa_joga_primeiro(void);
void t_xadrez_maquina_dificil_nao_espera_dezenas_de_voltas(void);
void t_xadrez_continuar_so_aparece_com_salvamento_valido(void);
void t_xadrez_ui_desenha_tabuleiro_e_pecas(void);
void t_xadrez_cancelar_promocao_nao_sai_da_partida(void);
void t_xadrez_ui_promocao_nao_mostra_texto_atras(void);
void t_xadrez_ui_centraliza_e_gira_peca_local(void);
void t_xadrez_ui_dama_tem_cinco_pontas_e_base_nitida(void);
void t_xadrez_ui_cheia_e_vazada_usam_a_mesma_silhueta(void);
void t_xadrez_v3_opcoes_menu_giro_e_historico(void);
void t_xadrez_v3_confirma_empate_e_abandono(void);
void t_xadrez_v3_mate_mostra_tabuleiro_antes_do_resultado(void);
void t_xadrez_ui_v3_desenha_opcoes_gaveta_e_resultado(void);
void t_xadrez_ui_v3_horizontal_usa_o_vidro_deitado(void);
void t_xadrez_v3_direcional_acompanha_horizontal_e_giro(void);
void t_xadrez_ui_historico_descreve_os_lances(void);
void t_xadrez_ui_icones_dizem_qual_acao_e_peca(void);
void t_xadrez_ui_capa_guia_a_escolha_da_partida(void);
void t_xadrez_ui_acoes_e_placar_sao_legiveis(void);
void t_xadrez_ajuda_e_ultima_jogada(void);
void t_xadrez_gaveta_alterna_ajuda_sem_trocar_tela(void);
void t_xadrez_revanche_repete_opcoes_e_troca_as_cores(void);

void t_liga_e_desenha(void);
void t_evento_de_dia_inteiro_aparece_e_vem_primeiro(void);
void t_o_dia_inteiro_fica_na_agenda(void);
void t_a_tarefa_feita_se_prende_ao_dia(void);
void t_o_item_guarda_fim_local_e_dia_inteiro(void);
void t_a_faixa_de_horario(void);
void t_paragrafo_cortado_diz_que_foi_cortado(void);
void t_a_reticencia_cabe_dentro_da_largura(void);
void t_a_proposta_nao_toca_no_cartao(void);
void t_confirmar_grava_e_enfileira(void);
void t_confirmar_apaga_o_audio_e_guarda_a_transcricao(void);
void t_anotacao_confirmada_nao_entra_na_fila(void);
void t_a_frase_longa_chega_inteira_ao_conferir(void);
void t_evento_do_google_e_so_leitura(void);
void t_evento_nao_oferece_marcar_feita(void);
void t_quando_oferece_os_dias_prontos(void);
void t_hora_e_de_evento_prazo_e_de_tarefa(void);
void t_as_telas_de_quando_cabem_no_quadro(void);
void t_o_hibrido_vale_em_todo_lugar(void);
void t_tirar_a_data_e_so_de_tarefa(void);
void t_anotacao_nao_vai_pro_google(void);
void t_tres_eventos(void);
void t_cursor_nao_passa_do_topo(void);
void t_a_carga_atualiza_a_topbar_por_faixa(void);
void t_cursor_para_na_ultima_linha(void);
void t_marcar_feita_sem_rede_enfileira(void);
void t_desmarcar_enfileira_o_estado_novo(void);
void t_cartao_falhou_entao_nada_aconteceu(void);
void t_a_acao_carrega_o_horario_do_gesto(void);
void t_marcar_cinco_vezes_e_um_estado(void);
void t_marca_item_de_outro_dia_no_lugar_certo(void);
void t_renomear_trava_o_titulo(void);
void t_renomear_trunca_em_vez_de_recusar(void);
void t_apagar_some_do_cartao_e_engole_a_fila(void);
void t_tarefa_com_hora_continua_tarefa(void);
void t_mudar_a_data_nao_move_o_item_de_pasta(void);
void t_mudar_a_hora_leva_o_fim_junto(void);
void t_ir_para_dia_troca_e_invalida(void);
void t_a_conversao_olha_o_cartao_nao_o_cache(void);
void t_ok_marca_a_tarefa_do_cursor(void);
void t_a_home_redesenha_com_o_cartao_novo(void);
void t_direita_entra_no_item_e_back_volta(void);
void t_direita_dentro_do_item_nao_empilha(void);
void t_travado_nao_anda(void);
void t_conteudo_nao_vira_tofu(void);
void t_texto_de_excecao_nao_vira_tofu(void);
void t_a_fonte_enorme_da_conta_do_cartaz(void);
void t_minha_conta_reconhece_wifi_sem_internet(void);
void t_a_citacao_e_mesmo_diferente_do_corpo(void);
void t_a_serifa_editorial_e_mesmo_outra_fonte(void);
void t_a_marca_dagua_e_tinta_cheia(void);
void t_a_transcricao_crua_aparece_sempre(void);
void t_a_origem_do_item_nao_se_sincroniza(void);
void t_concluir_mora_no_detalhe_da_tarefa(void);
void t_o_detalhe_diz_quando_a_tarefa_foi_concluida(void);
void t_o_detalhe_separa_data_e_prazo_da_tarefa(void);
void t_o_evento_diz_em_qual_agenda_mora(void);
void t_o_detalhe_quebra_o_valor_em_vez_de_cortar(void);
void t_apagar_alcanca_o_que_veio_do_google(void);
void t_um_so_detalhe_para_todo_tipo(void);
void t_o_detalhe_da_tarefa_responde(void);
void t_a_fala_original_desce_no_proprio_item(void);
void t_desmarcar_nao_abre_a_fala(void);
void t_abrir_tarefa_pela_lista_abre_a_tarefa_certa(void);
void t_o_gesto_em_voo_aparece_na_barra(void);
void t_destravar_devolve_a_tela_em_que_estava(void);
void t_fala_original_mostra_o_item_e_a_gravacao_inteira(void);
void t_anotacao_diz_que_e_so_no_aparelho(void);
void t_sem_ia_a_nota_abre_do_mesmo_jeito(void);
void t_sem_nem_transcricao_o_aviso_muda(void);
void t_a_duracao_sai_em_minutos_e_segundos(void);
void t_anotacoes_lista_por_recencia_agrupada_por_dia(void);
void t_anotacoes_vazia_convida_em_vez_de_calar(void);
void t_a_transcricao_vem_da_nota_e_nao_do_item(void);
void t_item_do_google_nao_tem_nota_nenhuma(void);
void t_dado_todo_ajuste_tem_chave_no_config(void);
void t_ajuste_grava_e_sobrevive_ao_reboot(void);
void t_ajuste_apara_em_vez_de_recusar(void);
void t_ajuste_igual_nao_escreve_de_novo(void);
void t_config_de_versao_antiga_usa_o_padrao(void);
void t_falar_pausar_retomar_e_confirmar(void);
void t_o_gesto_fisico_da_voz_respeita_o_modo_escolhido(void);
void t_a_transcricao_corre_como_fifo(void);
void t_capturar_nao_pergunta_nada(void);
void t_grava_de_qualquer_tela(void);
void t_sem_rede_o_botao_de_voz_recusa_na_hora(void);
void t_com_a_rede_de_volta_o_mesmo_botao_grava(void);
void t_a_voz_devolve_a_tela_de_onde_se_falou(void);
void t_o_resultado_so_aparece_depois_da_resposta(void);
void t_back_segurado_encerra_a_volta_da_voz(void);
void t_descartar_pergunta_com_o_nao_selecionado(void);
void t_descartar_confirmado_nao_deixa_rastro(void);
void t_pausado_o_medidor_zera_mas_a_tela_fica(void);
void t_o_log_registra_duracao_e_nunca_conteudo(void);
void t_depois_do_ok_a_faixa_estrutura_e_o_aparelho_trava(void);
void t_a_resposta_fecha_a_faixa_e_abre_o_recibo(void);
void t_sem_resposta_a_faixa_destrava_e_diz_onde_a_fala_esta(void);
void t_envio_que_nao_saiu_descarta_e_diz_a_verdade(void);
void t_estruturando_diz_e_pisca(void);
void t_gravar_que_nao_comeca_diz_por_que(void);
void t_conferir_so_sai_decidindo(void);
void t_o_id_da_fala_e_o_do_comeco(void);
void t_nenhuma_falha_deixa_gravacao_no_cartao(void);
void t_prazo_da_tela_e_maior_que_o_da_conexao(void);
void t_o_panico_funciona_durante_a_estruturacao(void);
void t_a_faixa_sem_resposta_sai_com_qualquer_botao(void);
void t_pausar_nao_gasta_whisper(void);
void t_o_id_com_dois_pontos_grava_e_volta_inteiro(void);
void t_o_que_a_fala_criou_mora_no_dia_do_evento(void);
void t_confirmar_apaga_a_captura_crua(void);
void t_descartar_apaga_mesmo_a_gravacao(void);
void t_tarefa_sem_data_continua_no_dia_da_fala(void);
void t_o_gesto_troca_o_id_provisorio_pelo_do_google(void);
void t_uma_fala_com_tres_acoes_nao_duplica_nenhuma(void);
void t_gesto_de_edicao_nao_mexe_no_id(void);
void t_o_pull_derruba_as_marcas_do_calendario(void);
void t_e2e_a_serie_diaria_chega_ao_mes_inteiro(void);
void t_o_lote_em_pedacos_nao_repinta_a_cada_pedaco(void);
void t_lote_que_termina_vazio_ainda_rele_a_tela(void);
void t_e2e_a_rotina_marca_o_mes_com_uma_linha(void);
void t_o_dia_distante_e_consulta_e_nao_vai_para_o_cartao(void);
void t_a_consulta_do_dia_sobrevive_ao_recarregamento(void);
void t_o_mes_pedido_sai_uma_vez_e_morre_na_resposta(void);
void t_o_item_do_dia_consultado_abre_e_marca(void);
void t_e2e_abrir_um_dia_passado_pede_e_mostra(void);
void t_apagado_no_google_some_de_qualquer_dia(void);
void t_a_tarefa_apagada_no_google_some_da_tela(void);
void t_o_cursor_nao_passa_por_cima_de_um_lote_que_falhou(void);
void t_o_cursor_avanca_quando_o_lote_grava(void);
void t_sincronizar_nao_apaga_a_fala_que_originou_o_item(void);
void t_desconectar_preserva_e_outra_conta_limpa(void);
void t_voltar_do_calendario_devolve_a_home_de_hoje(void);
void t_dia_futuro_vazio_nao_anuncia_secao(void);
void t_dia_futuro_com_compromisso_diz_quando(void);
void t_a_fala_do_mes_mostra_o_numero_e_o_que_sobra(void);
void t_esgotado_mostra_zero(void);
void t_o_numero_grande_cabe_e_so_tem_digitos(void);
void t_sem_conta_a_fala_do_mes_nao_inventa_numero(void);
void t_ajustes_abre_a_fala_do_mes(void);
void t_armazenamento_sai_em_gb_com_uma_casa(void);
void t_cartao_quase_vazio_sai_em_mb(void);
void t_espaco_desconhecido_nao_vira_zero(void);

void t_a_agenda_anuncia_a_saida_no_rodape(void);
void t_a_gaveta_fecha_em_vez_de_voltar(void);
void t_a_agenda_leva_o_dia_no_cabecalho(void);
void t_o_cabecalho_segue_o_dia_visto(void);
void t_o_local_aparece_em_qualquer_evento(void);
void t_o_cabecalho_do_dia_nao_encavala(void);
void t_o_calendario_tem_a_moldura_da_agenda(void);
void t_o_resumo_do_calendario_conta_em_palavras(void);
void t_o_dia_vazio_nao_promete_a_semana(void);
void t_o_hud_distingue_subir_de_descer_de_falhar(void);

void t_refresco_o_foco_e_parcial_mesmo_medindo_muito(void);
void t_refresco_mover_o_foco_na_home_declara_a_intencao(void);
void t_chrome_a_barra_nao_e_uma_faixa_preta(void);
void t_chrome_a_barra_continua_dizendo_as_coisas(void);
void t_chrome_o_rodape_e_claro_quando_nada_acontece(void);
void t_chrome_nenhuma_tela_assenta_o_proprio_seletor(void);
void t_chrome_o_evento_em_foco_inverte_so_o_conteudo(void);
void t_chrome_o_canto_nao_danca_com_o_sync(void);
void t_chrome_muitas_tarefas_nao_quebram_a_tela(void);

void t_lancador_o_aparelho_liga_na_home(void);
void t_o_cabecalho_diz_o_nome_e_nao_o_email(void);
void t_lancador_o_ok_abre_a_agenda(void);
void t_lancador_entrar_na_agenda_pede_o_delta(void);
void t_lancador_o_back_na_home_nao_cria_tela(void);
void t_lancador_a_grade_anda_em_duas_dimensoes(void);
void t_lancador_cada_cartao_abre_a_sua_area(void);
void t_lancador_voltar_devolve_o_cartao_de_onde_se_saiu(void);
void t_lancador_o_menu_nao_abre_gaveta_na_home(void);
void t_lancador_a_vista_monta_os_quatro_cartoes(void);
void t_lancador_a_vista_leva_o_foco_do_estado(void);
void t_lancador_a_saudacao_segue_a_hora(void);
void t_lancador_sem_hora_a_saudacao_nao_inventa(void);
void t_lancador_o_rodape_nao_promete_back(void);
void t_lancador_a_barra_mostra_a_data(void);
void t_lancador_o_foco_preenche_o_cartao(void);
void t_lancador_mover_o_foco_troca_o_bloco_preto(void);
void t_lancador_a_grade_cabe_sem_invadir_a_moldura(void);
void t_lancador_cada_cartao_desenha_icone_e_textos(void);
void t_lancador_o_texto_do_cartao_cabe_no_cartao(void);
void t_lancador_o_completo_nao_assenta_o_cartao_em_foco(void);
void t_lancador_entrar_em_ajustes_mede_a_memoria(void);
void t_lancador_a_agenda_anda_um_dia_para_cada_lado(void);
void t_lancador_voltar_para_a_agenda_devolve_hoje(void);
void t_lancador_as_tarefas_nao_mudam_com_o_dia(void);
void t_lancador_um_dia_sem_pasta_nao_herda_o_dia_anterior(void);
void t_lancador_a_contagem_regressiva_so_existe_hoje(void);
void t_lancador_a_agenda_nao_abre_o_detalhe_do_dia(void);

void t_grid_icone_de_lista_cabe_na_linha(void);
void t_acervo_o_lote_do_servidor_vira_obra_no_cartao(void);
void t_acervo_catalogo_igual_nao_regrava_o_cartao(void);
void t_acervo_obra_removida_online_continua_local(void);
void t_acervo_obra_apenas_online_some_com_o_catalogo(void);
void t_acervo_percorre_todos_os_lotes_antes_de_remover(void);
void t_acervo_o_texto_so_vira_obra_se_chegar_inteiro(void);
void t_acervo_baixa_em_blocos_sem_prender_a_navegacao(void);
void t_acervo_retoma_o_part_depois_de_reiniciar(void);
void t_acervo_reiniciar_retomara_depois_de_confirmar_catalogo(void);
void t_acervo_sync_nao_pisca_o_estado_online(void);
void t_acervo_cartao_cheio_nao_comeca_download(void);
void t_acervo_o_part_sobrevive_ao_reboot_sem_virar_obra(void);
void t_acervo_a_rede_cair_no_meio_nao_deixa_obra_falsa(void);
void t_acervo_erro_do_servidor_solta_a_obra_na_hora(void);
void t_leitor_pagina_sem_cortar_palavra(void);
void t_leitor_nao_corta_caractere_utf8(void);
void t_leitor_trocar_a_fonte_preserva_a_posicao(void);
void t_leitor_a_letra_maior_pagina_menos(void);
void t_leitor_voltar_devolve_a_mesma_pagina(void);
void t_leitor_o_fim_nao_passa_do_fim(void);
void t_leitor_a_ultima_pagina_nunca_vira_branco(void);
void t_leitor_a_porcentagem_vem_do_offset(void);
void t_leitor_reabre_onde_parou(void);
void t_leitor_a_pagina_cabe_na_tela(void);
void t_leitor_conta_as_paginas_da_obra(void);
void t_leitor_usa_flash_na_capa_e_parcial_entre_textos(void);
void t_leitor_menu_tem_alinhamento(void);
void t_acervo_navega_a_home_abre_o_acervo(void);
void t_acervo_navega_ao_entrar_pede_o_catalogo_online(void);
void t_acervo_navega_a_gaveta_e_do_acervo(void);
void t_acervo_navega_o_ok_abre_o_que_esta_aqui(void);
void t_acervo_navega_continuar_lendo_e_um_foco_real(void);
void t_acervo_navega_continuar_lembra_a_ultima_do_mesmo_dia(void);
void t_acervo_navega_a_obra_remota_comeca_a_baixar(void);
void t_acervo_navega_mantem_a_obra_do_cursor_visivel(void);
void t_acervo_navega_as_setas_viram_pagina(void);
void t_acervo_navega_o_livro_devolve_a_memoria(void);
void t_acervo_a_capa_desce_depois_do_texto(void);
void t_contrato_o_lote_do_backend_e_lido_inteiro(void);
void t_contrato_o_lote_vazio_nao_e_erro(void);
void t_contrato_o_id_volta_igual_do_cartao(void);
void t_contrato_o_tamanho_do_lote_confere_a_copia(void);
void t_acervo_ui_cabe_no_quadro(void);
void t_acervo_ui_cabecalhos_tem_icones_legiveis(void);
void t_acervo_ui_miniatura_nao_cobre_biblioteca(void);
void t_obra_ui_sinopse_longa_rola_sem_ser_cortada(void);
void t_acervo_ui_a_linha_tem_area_propria(void);
void t_acervo_ui_o_vazio_aparece_escrito(void);
void t_acervo_ui_o_vazio_mostra_um_livro(void);
void t_acervo_ui_o_titulo_do_vazio_e_centrado(void);
void t_acervo_ui_o_vazio_mostra_o_qr_do_aplicativo(void);
void t_acervo_vista_continuar_lendo_e_a_ultima_aberta(void);
void t_acervo_vista_a_legenda_muda_com_o_progresso(void);
void t_acervo_vista_o_icone_diz_o_que_o_OK_faz(void);
void t_acervo_vista_vazio_explica(void);
void t_acervo_vista_filtra_sem_perder_o_resto(void);
void t_acervo_guarda_os_tres_estados(void);
void t_acervo_separa_transferencia_de_leitura(void);
void t_acervo_lista_da_mais_recente_para_a_mais_antiga(void);
void t_acervo_ignora_o_que_esta_pela_metade(void);
void t_acervo_remove_so_a_copia_local(void);
void t_acervo_descarta_local_sem_apagar_a_origem_online(void);
void t_acervo_o_clique_marca_baixando_na_mesma_hora(void);
void t_mapa_a_sentinela_alcanca_a_ultima_tela(void);
void t_mapa_toda_tela_esta_declarada(void);
void t_mapa_tela_de_leitura_nao_pinta_seletor(void);

void t_grid_a_barra_ocupa_a_mesma_altura_em_toda_tela(void);
void t_grid_o_canto_de_estado_e_identico_entre_telas(void);
void t_grid_a_faixa_e_um_retangulo_so(void);
void t_grid_as_zonas_cobrem_a_tela_sem_encostar(void);
void t_grid_a_largura_util_fecha_com_a_margem(void);
void t_grid_nenhuma_tela_pede_glifo_que_nao_existe(void);
void t_grid_trocar_de_tela_nao_deixa_resto(void);
void t_grid_sair_do_teclado_nao_deixa_o_teclado(void);
void t_grid_fechar_a_faixa_devolve_a_tela_inteira(void);

void t_faixa_limpa_o_chao_antes_de_escrever(void);
void t_faixa_nao_escreve_fora_do_retangulo(void);
void t_faixa_nunca_cobre_a_barra_nem_o_topo_do_miolo(void);
void t_faixa_negativa_inverte_a_faixa_inteira(void);
void t_faixa_os_tres_usos_dividem_a_mesma_geometria(void);
void t_faixa_botao_comprido_trunca_dentro_da_faixa(void);
void t_faixa_a_gaveta_nao_vaza_por_cima_do_conteudo(void);
void t_faixa_na_gaveta_o_texto_cede_espaco_ao_valor(void);
void t_faixa_o_conteudo_nao_encosta_nos_botoes(void);
void t_o_aparelho_mede_a_memoria_ao_ligar(void);
void t_o_rotulo_nao_invade_a_coluna_do_valor(void);
void t_o_sobre_diz_de_quem_e_o_aparelho(void);
void t_o_botao_de_voz_alterna_na_propria_linha(void);
void t_a_lista_de_redes_diz_forca_e_quais_estao_salvas(void);
void t_rede_aberta_conecta_sem_pedir_senha(void);
void t_o_hud_diz_quando_o_aparelho_esta_esperando(void);
void t_esquecer_a_rede_apaga_a_senha_e_desconecta(void);
void t_o_cursor_pula_as_linhas_que_so_informam(void);
void t_esquecer_cabe_inteiro_na_linha(void);
void t_procurando_diz_que_esta_procurando(void);
void t_entrar_no_wifi_manda_procurar(void);
void t_escolher_uma_rede_nova_pede_a_senha(void);
void t_rede_oculta_pede_o_nome_e_depois_a_senha(void);
void t_a_rede_conectada_fica_guardada(void);
void t_sem_rede_guardada_o_boot_segue(void);
void t_a_lista_marca_a_rede_conhecida(void);
void t_o_indice_responde_sem_tocar_o_cartao(void);
void t_o_indice_anda_com_a_escrita(void);
void t_a_poda_mantem_o_cartao_do_tamanho_da_janela(void);
void t_as_marcas_do_mes_vem_do_servidor(void);
void t_apagar_nao_deixa_pasta_para_tras(void);
void t_rotina_todo_dia(void);
void t_rotina_dias_da_semana(void);
void t_rotina_mes_e_ano(void);
void t_rotina_acaba_e_tem_buraco(void);
void t_rotina_sem_regra_e_regra_estranha(void);
void t_rotina_em_palavras(void);
void t_o_contrato_le_um_evento(void);
void t_o_contrato_sabe_o_que_se_repete(void);
void t_o_cursor_nao_atravessa_o_fim_do_array(void);
void t_dia_inteiro_vence_a_hora(void);
void t_a_tarefa_traz_data_e_estado(void);
void t_item_sem_id_nao_entra(void);
void t_o_pull_percorre_a_lista_inteira(void);
void t_o_pull_grava_no_cartao_e_derruba_o_cache(void);
void t_o_primeiro_boot_registra_o_aparelho(void);
void t_o_token_fica_no_cofre_e_vale_no_boot_seguinte(void);
void t_o_cartao_nao_guarda_mais_prova_nem_token(void);
void t_o_cartao_velho_migra_prova_e_token(void);
void t_a_prova_nao_muda_entre_boots(void);
void t_ao_ligar_ele_descobre_o_dono_e_puxa_o_dia(void);
void t_desvincular_avisa_o_servidor_antes_de_esquecer(void);
void t_restaurar_desvincula_antes_de_formatar(void);
void t_evento_falado_sobrevive_ao_reinicio(void);
void t_boot_sem_hora_nao_poda_o_cartao(void);
void t_tarefa_com_hora_falada_sobrevive_ao_reinicio(void);
void t_o_gesto_carrega_o_id_da_operacao(void);
void t_o_pull_traz_o_fuso_da_conta(void);
void t_a_captura_volta_com_as_acoes_propostas(void);
void t_captura_sem_acao_ainda_traz_a_frase(void);
void t_o_gesto_sobe_um_por_vez(void);
void t_o_gesto_nao_espera_o_pull_pendurado(void);
void t_da_fala_ate_a_home_mudar(void);
void t_renomear_e_apagar_sobem_pro_google(void);
void t_apagar_offline_e_o_pull_nao_ressuscita(void);
void t_gesto_recusado_avisa_no_vidro(void);
void t_gesto_antigo_pede_a_verdade_inteira_do_google(void);
void t_a_captura_espera_a_linha_vagar(void);
void t_a_voz_apaga_o_que_ja_existe(void);
void t_a_voz_edita_sem_duplicar(void);
void t_a_fila_sobrevive_ao_boot(void);
void t_anotacao_nao_vira_gesto_no_google(void);
void t_descartar_a_proposta_nao_sobe_nada(void);
void t_o_codigo_de_pareamento_chega_do_servidor(void);
void t_sem_rede_nao_se_tenta_sincronizar(void);
void t_nunca_falou_diz_nunca(void);
void t_o_armazenamento_diz_o_que_ocupa(void);
void t_cartao_quase_cheio_avisa_sem_apagar_nada(void);
void t_armazenamento_sem_medida_nao_inventa(void);
void t_entrar_no_armazenamento_mede_o_cartao(void);
void t_apagar_pergunta_antes_e_nasce_no_nao(void);
void t_desistir_de_apagar_volta_pra_vida_normal(void);
void t_so_o_sim_deliberado_apaga(void);
void t_sem_rede_a_conexao_manda_ligar_o_wifi(void);
void t_com_rede_e_sem_conta_a_tela_espera_o_codigo(void);
void t_pareado_a_tela_diz_a_conta_e_a_fila(void);
void t_conta_conectada_da_acesso_ao_aplicativo(void);
void t_ajustes_abre_minha_conta(void);
void t_vincular_espera_o_codigo_em_vez_de_inventar(void);
void t_vincular_manda_logar_antes_de_digitar(void);
void t_desconectar_nasce_no_nao_e_diz_o_que_fica(void);
void t_o_primeiro_uso_diz_que_esta_conectando_antes_da_conta(void);
void t_as_fases_de_rede_e_conta_desenham_alguma_coisa(void);
void t_a_lista_traz_quantos_tem_e_quantos_foram(void);
void t_o_item_diz_de_que_fala_ele_veio(void);
void t_com_ntp_e_conta_nada_no_relogio_se_ajusta_a_mao(void);
void t_o_cartao_vazio_pede_a_colheita_inteira(void);
void t_cada_rota_sai_com_o_metodo_que_o_servidor_espera(void);
void t_cadastrado_no_painel_o_codigo_aparece_sozinho(void);
void t_o_codigo_nao_e_pedido_com_a_tela_fechada(void);
void t_o_aparelho_nao_fala_https_antes_de_saber_a_hora(void);
void t_token_recusado_faz_o_aparelho_se_registrar_de_novo(void);
void t_a_prova_que_sobe_e_a_que_fica_no_cofre_sao_a_mesma(void);
void t_o_tinto_sem_token_tenta_de_novo_ate_se_registrar(void);
void t_as_agendas_chegam_e_enchem_a_tela(void);
void t_a_busca_de_agendas_espera_a_vez_em_vez_de_sumir(void);
void t_a_busca_de_agendas_desiste_e_oferece_tentar_de_novo(void);
void t_a_busca_de_agendas_anima_os_pontinhos(void);
void t_o_gesto_nao_atropela_o_pull_em_voo(void);
void t_a_linha_da_nuvem_se_solta_sozinha(void);
void t_marcar_agenda_espera_a_vez_em_vez_de_sumir(void);
void t_o_interruptor_vira_quando_o_servidor_confirma(void);
void t_o_interruptor_avisa_que_esta_indo_antes_de_virar(void);
void t_desligar_uma_agenda_apaga_o_que_ela_ja_tinha_trazido(void);
void t_um_pull_comum_nao_apaga_nada(void);
void t_grid_nenhum_rotulo_e_cortado_no_meio_de_um_caractere(void);
void t_o_paragrafo_obedece_a_quebra_de_linha(void);
void t_a_home_vazia_diz_que_esta_vazia(void);
void t_a_marca_dagua_e_mais_clara_que_a_tinta_cheia(void);
void t_o_dia_vazio_usa_a_mesma_marca_dagua(void);
void t_o_dia_tem_duas_secoes_e_nenhuma_e_captura(void);
void t_o_dia_lista_em_ordem_crescente_de_horario(void);
void t_a_gravacao_nao_entra_na_regua_do_dia(void);
void t_item_sem_titulo_nunca_aparece_em_branco(void);
void t_tarefa_aparece_da_data_ate_o_prazo(void);
void t_tarefa_com_hora_nao_vira_atrasada(void);
void t_o_calendario_tem_uma_legenda_so_e_e_a_do_google(void);
void t_a_tira_mostra_o_que_o_dia_sob_o_cursor_tem(void);
void t_o_mes_vazio_diz_o_nome_do_mes(void);
void t_a_tira_acompanha_o_cursor_na_grade(void);
void t_andar_um_dia_na_grade_le_o_dia_e_mais_nada(void);
void t_todo_estado_do_vinculo_diz_alguma_coisa(void);
void t_as_recusas_do_gesto_dizem_o_remedio_certo(void);
void t_o_cursor_pula_as_linhas_que_nao_se_apertam(void);
void t_do_repouso_ate_o_qr_sem_perder_nenhum_gesto(void);
void t_pilha_cheia_troca_o_topo_em_vez_de_sumir(void);
void t_sincronizacao_sem_conta_explica_em_vez_de_ficar_vazia(void);
void t_sincronizacao_lista_agendas_e_o_que_esta_ligado(void);
void t_a_hora_pela_internet_desliga_o_ajuste_a_mao(void);
void t_a_hora_de_12_horas_diz_am_e_pm(void);
void t_a_hora_do_item_tambem_obedece_ao_ajuste(void);
void t_a_barra_segue_o_ajuste_de_hora(void);
void t_o_campo_de_hora_segue_o_formato_escolhido(void);
void t_desligada_a_rede_os_campos_ficam_editaveis(void);
void t_ajustar_a_hora_a_mao_muda_o_relogio_do_aparelho(void);
void t_o_ajuste_a_mao_parte_da_hora_atual_e_usa_os_dois_eixos(void);
void t_o_dia_respeita_o_tamanho_do_mes(void);
void t_sem_hora_valida_os_campos_comecam_numa_data_sensata(void);
void t_no_primeiro_uso_o_direcional_escolhe_o_campo(void);
void t_ok_no_fuso_nao_grava_o_relogio(void);
void t_sem_tocar_em_nada_a_tela_trava_sozinha(void);
void t_bloqueio_automatico_pode_ser_desligado(void);
void t_gravando_a_tela_nao_trava_por_tempo(void);
void t_no_primeiro_uso_a_tela_nao_trava_por_tempo(void);
void t_o_interruptor_da_hora_pela_rede_liga_e_desliga(void);
void t_ligar_a_hora_pela_rede_pergunta_na_hora(void);
void t_o_fuso_se_ajusta_e_vale_com_o_ntp_ligado(void);

void t_voz_bloqueada_pede_desbloqueio(void);
void t_sem_minutos_recusa_e_leva_a_voz(void);
void t_conta_caida_manda_reconectar_e_nao_esperar(void);
void t_google_revogado_mantem_conta_e_pede_novo_login(void);
void t_o_aviso_de_reconectar_nao_insiste(void);
void t_hal_sem_microfone_nao_derruba_o_aparelho(void);
void t_sem_cartao_o_aparelho_diz_e_nao_finge(void);
void t_cartao_virgem_nao_bloqueia(void);
void t_marcar_derruba_todos_os_caches(void);
void t_falha_de_listagem_chega_ao_estado_do_app(void);
void t_tarefa_futura_de_outro_dia_aparece_hoje(void);
void t_dia_passado_nao_recebe_pendencia(void);
void t_o_calendario_marca_o_mes_inteiro(void);
void t_o_calendario_ve_alem_da_primeira_pagina(void);
void t_evento_de_varios_dias_ocupa_todos_eles(void);
void t_descartar_invalida_o_cache(void);
void t_item_que_nao_cabe_e_contado(void);
void t_menu_abre_e_fecha_a_gaveta(void);
void t_esquerda_nao_volta(void);
void t_back_fecha_a_gaveta_antes_de_voltar(void);
void t_gaveta_e_submenu_da_pagina(void);
void t_o_menu_abre_as_acoes_do_item(void);
void t_item_ilegivel_aparece_na_agenda(void);
void t_o_dia_do_calendario_lista_tarefas_como_a_agenda(void);
void t_tarefa_concluida_mora_no_dia_da_conclusao(void);
void t_as_telas_de_tarefa_leem_a_mesma_fonte(void);
void t_o_navegador_de_dia_mostra_que_esta_em_foco(void);
void t_confirmar_guarda_o_que_a_tela_de_resultado_vai_listar(void);
void t_conferir_tem_o_kicker_e_o_cartao_de_tres_linhas(void);
void t_captura_e_apagada_no_dia_em_que_nasceu(void);
void t_confirmar_duas_vezes_nao_manda_duas_vezes(void);
void t_coluna_do_campo_nao_encosta_no_valor(void);
void t_o_valor_do_campo_nao_perde_dado_para_a_enfase(void);
void t_o_detalhe_rola_quando_nao_cabe(void);
void t_a_raiz_de_ajustes_sao_cinco_destinos(void);
void t_minha_conta_tem_quatro_estados(void);
void t_minha_conta_nao_rola_em_nenhum_estado(void);
void t_o_proprietario_se_troca_em_qualquer_estado(void);
void t_sincronizacao_mostra_o_card_e_as_agendas(void);
void t_doze_agendas_paginam_e_as_de_fora_sao_ditas(void);
void t_buscando_agendas_e_o_mesmo_card_com_pontinhos(void);
void t_aparencia_no_desenho_da_fase_3(void);
void t_som_no_desenho_da_fase_3(void);
void t_armazenamento_no_desenho_da_fase_3(void);
void t_sobre_no_desenho_da_fase_3(void);
void t_restaurar_diz_o_que_sai_e_o_que_fica(void);
void t_preparando_mostra_as_etapas(void);
void t_restaurar_usa_a_confirmacao_do_sistema(void);
void t_o_sobre_tem_porta_no_armazenamento(void);
void t_a_capa_diz_o_que_vem(void);
void t_a_hora_se_corrige_sozinha_com_rede(void);
void t_a_conclusao_mostra_as_tres_verificacoes(void);
void t_a_rolagem_anda_de_pagina_inteira(void);
void t_virar_pagina_chega_ao_vidro_como_tela_nova(void);
void t_mover_o_cursor_nunca_paga_refresh_completo(void);
void t_o_pull_de_fundo_nao_anima_a_barra(void);
void t_o_back_diz_para_onde_volta(void);
void t_o_desenho_nao_espera_a_fila_esvaziar(void);
void t_tres_acoes_de_uma_fala_sobem_todas(void);
void t_o_resultado_so_entra_quando_a_fila_esvazia(void);
void t_a_fala_nao_espera_a_rede_voltar(void);
void t_o_servidor_so_pode_ser_https(void);
void t_o_contrato_cabe_nos_buffers_do_device(void);
void t_voltar_da_rede_continua_pelo_delta(void);
void t_eventos_wifi_seguidos_nao_reiniciam_o_ntp(void);
void t_sem_rede_nao_se_grava(void);
void t_rede_que_cai_no_meio_da_fala_descarta_o_audio(void);
void t_rede_que_cai_estruturando_descarta_na_hora(void);
void t_rede_que_cai_no_conferir_descarta_a_proposta(void);
void t_a_paginacao_conta_as_paginas_num_lugar_so(void);
void t_os_menus_paginam_em_vez_de_deslizar(void);
void t_a_legenda_pesa_na_conta_da_pagina(void);
void t_a_pagina_diz_onde_acaba_e_nao_so_onde_comeca(void);
void t_a_tela_bloqueada_no_desenho_da_fase_3(void);
void t_a_tela_bloqueada_diz_dia_livre(void);
void t_bloqueio_mostra_so_hoje_pelo_nome(void);
void t_o_contador_de_pagina_mostra_a_direcao(void);
void t_o_rodape_anima_a_espera(void);
void t_o_detalhe_nao_corta_o_titulo(void);
void t_o_dia_pagina_quando_tem_coisa_demais(void);
void t_o_cartao_e_varrido_uma_vez_por_quadro(void);
void t_montar_duas_vezes_le_o_cartao_uma_vez(void);
void t_nenhum_compromisso_do_dia_fica_de_fora(void);
void t_conexao_conectada_mostra_o_card_e_as_acoes(void);
void t_conexao_sem_rede_salva_nao_oferece_esquecer(void);
void t_o_sinal_do_wifi_nao_congela_na_conexao(void);
void t_a_oscilacao_do_sinal_nao_gasta_tinta(void);
void t_a_senha_do_wifi_nao_mora_no_cartao(void);
void t_o_cartao_velho_migra_a_senha_e_se_limpa(void);
void t_a_lista_de_redes_poe_o_que_se_sabe_na_legenda(void);
void t_a_busca_de_redes_anima_os_pontinhos(void);
void t_senha_recusada_e_sem_resposta_sao_telas_diferentes(void);
void t_senha_recusada_nao_fica_tentando_sozinha(void);
void t_conectando_anima_os_pontinhos(void);
void t_esquecer_rede_pergunta_antes(void);
void t_lista_de_redes_vazia_explica_e_oferece_saida(void);
void t_a_tela_de_senha_diz_a_rede_e_conta_os_caracteres(void);
void t_sincronizacao_separa_os_dois_erros(void);
void t_marca_de_tarefa_sai_do_prazo(void);
void t_a_tira_do_calendario_nao_sobrepoe(void);
void t_a_contagem_da_tira_conta_o_que_o_dia_mostra(void);
void t_o_calendario_mostra_a_concluida_no_dia_da_conclusao(void);
void t_a_linha_da_tira_nao_chama_feita_de_por_fazer(void);
void t_back_segurado_volta_pra_home(void);
void t_cartao_le_o_que_escreveu(void);
void t_docar_chega_no_estado(void);
void t_pinagem_final_dos_botoes(void);
void t_uc8253_inicia_com_a_configuracao_do_painel(void);
void t_uc8253_gira_o_framebuffer_para_o_gabinete(void);
void t_uc8253_primeiro_quadro_faz_refresh_completo(void);
void t_uc8253_o_plano_velho_e_escrito_depois_do_refresh(void);
void t_uc8253_dois_quadros_deixam_a_referencia_em_dia(void);
void t_uc8253_parcial_entra_no_modo_parcial(void);
void t_uc8253_parcial_usa_a_waveform_de_fabrica(void);
void t_uc8253_parcial_desfaz_a_temperatura_forcada(void);
void t_uc8253_parcial_separa_as_tres_operacoes(void);
void t_uc8253_a_faxina_leva_o_vidro_aos_extremos(void);
void t_uc8253_a_faxina_nao_finge_temperatura(void);
void t_uc8253_o_completo_tambem_usa_a_waveform_nativa(void);
void t_uc8253_nao_desliga_o_painel_entre_dois_quadros(void);
void t_uc8253_desliga_manda_power_off(void);
void t_uc8253_faixa_pinta_so_a_faixa(void);
void t_tick_com_a_tela_parada_nao_pede_quadro(void);
void t_tick_que_vira_o_minuto_pede_quadro(void);
void t_tick_gravando_pede_quadro(void);
void t_gesto_sem_rede_acontece_e_espera_na_fila(void);
void t_mudar_a_data_pela_mao(void);
void t_escolher_no_mes_tem_rota_propria(void);
void t_a_confirmacao_volta_para_onde_a_pessoa_estava(void);
void t_o_mostrador_marca_qualquer_hora(void);
void t_tarefa_com_hora_vive_na_regua_e_se_marca(void);
void t_motor_a_mesma_tela_e_um_quadro_so(void);
void t_motor_tela_sem_cursor_nao_paga_o_segundo_quadro(void);
void t_motor_tela_com_cursor_pinta_o_seletor_depois(void);
void t_motor_abrir_caixa_limpa_o_chao_antes(void);
void t_motor_fechar_caixa_e_um_quadro_so(void);
void t_motor_trocar_de_tela_com_caixa_nao_soma_os_dois_rituais(void);
void t_motor_nunca_devolve_plano_vazio(void);
void t_refresco_quadro_que_muda_muito_pede_completo(void);
void t_eink_sair_do_teclado_repinta_inteiro(void);
void t_memoria_distingue_ausencia_de_filesystem(void);
void t_memoria_distingue_diretorio_vazio_de_falha(void);
void t_memoria_informa_tipo_do_caminho(void);
void t_memoria_injeta_falha_ao_criar_diretorio(void);
void t_memoria_lista_diretorio_vazio_criado(void);
void t_memoria_nao_confunde_prefixo_com_diretorio_pai(void);
void t_memoria_cheia_e_observavel_e_apagar_recupera(void);
void t_memoria_cheia_ou_somente_leitura_continua_legivel(void);
void t_arvore_ausente_e_virgem(void);
void t_arvore_sem_formato_e_danificada(void);
void t_arvore_com_raiz_de_arquivo_e_danificada(void);
void t_arvore_de_versao_futura_nao_e_tocada(void);
void t_arvore_sem_uma_pasta_e_parcial(void);
void t_prepara_nao_toca_no_que_esta_fora_da_raiz(void);
void t_prepara_propaga_falha_de_cada_operacao(void);
void t_formato_anterior_sobrevive_ao_rename_falho(void);
void t_prova_de_escrita_nao_deixa_residuo(void);
void t_prova_de_escrita_limpa_residuo_do_boot_anterior(void);
void t_prova_de_escrita_denuncia_memoria_travada(void);
void t_arvore_vazia_e_virgem_e_nao_reparo(void);
void t_arvore_com_arquivo_alheio_continua_danificada(void);
void t_perfil_ausente_nao_e_formato_invalido(void);
void t_perfil_grava_e_rele_o_schema_exato(void);
void t_perfil_nao_regenera_id_de_cartao_que_ja_tem_dono(void);
void t_perfil_id_tem_32_hex(void);
void t_perfil_trunca_nome_sem_partir_utf8(void);
void t_perfil_rename_falho_nao_deixa_perfil_pela_metade(void);
void t_gravar_item_cria_as_pastas_do_caminho(void);
void t_memoria_virgem_vai_para_boas_vindas(void);
void t_o_voltar_anda_para_tras_no_trecho(void);
void t_voltar_da_conclusao_nao_abre_data_e_hora_vazia(void);
void t_pular_o_wifi_e_voltar_reabre_o_wifi(void);
void t_voltar_para_o_wifi_conectado_e_seguir_volta_a_conta(void);
void t_voltar_para_a_conta_ja_vinculada_diz_conectada(void);
void t_a_primeira_etapa_nao_tem_para_onde_voltar(void);
void t_o_diagnostico_de_midia_nao_volta(void);
void t_o_voltar_so_anda_dentro_do_primeiro_uso(void);
void t_o_relogio_anda_fora_da_home(void);
void t_o_minuto_pede_quadro_o_segundo_nao(void);
void t_cada_defeito_da_midia_tem_fase_propria(void);
void t_formato_futuro_nao_oferece_reparo(void);
void t_arvore_danificada_vai_para_reparo(void);
void t_antes_da_home_nenhum_botao_escapa(void);
void t_boas_vindas_abre_o_nome(void);
void t_reboot_retoma_na_primeira_pendencia(void);
void t_desligar_sem_nome_volta_para_as_boas_vindas(void);
void t_onboarding_concluido_abre_a_home(void);
void t_formatar_faz_o_radio_esquecer_a_rede(void);
void t_caixa_alta_redesenha_na_hora(void);
void t_power_no_primeiro_uso_trava_e_destrava(void);
void t_restaurar_reinicia_o_chip(void);
void t_back_da_conexao_no_primeiro_uso_diz_voltar(void);
void t_primeiro_uso_escuta_o_relogio_e_se_apresenta(void);
void t_conta_sem_resposta_tem_saida(void);
void t_wifi_no_primeiro_uso_pede_a_hora(void);
void t_primeiro_uso_se_reapresenta_sozinho(void);
void t_fluxo_do_primeiro_uso_de_ponta_a_ponta(void);
void t_reiniciar_religa_a_rede_e_nao_pede_a_hora(void);
void t_a_conclusao_diz_o_que_ficou_faltando(void);
void t_aparelho_configurado_nao_repete_o_primeiro_uso(void);
void t_reparo_nao_destrutivo_nao_apaga_nada(void);
void t_formatar_exige_dois_gestos_e_a_pergunta_nasce_no_nao(void);
void t_so_o_sim_deliberado_formata(void);
void t_voltar_da_confirmacao_nao_apaga(void);
void t_ausencia_e_comunicacao_nunca_oferecem_formatar(void);
void t_a_tela_de_preparacao_aparece_antes_de_formatar(void);
void t_logo_vem_do_asset_oficial(void);
void t_cartao_removido_em_uso_cai_na_tela_de_memoria(void);
void t_gravacao_nao_continua_sem_onde_escrever(void);
void t_mutacoes_respeitam_estado_da_memoria(void);

void t_data_ida_e_volta(void);
void t_data_atravessa_o_mes(void);
void t_dia_da_semana(void);
void t_json_le_o_contrato(void);
void t_json_nao_confunde_chave_com_valor(void);
void t_json_trunca_em_vez_de_rejeitar(void);
void t_cartao_grava_e_le_igual(void);
void t_cartao_tres_dias_doze_itens(void);
void t_corte_de_energia_nao_deixa_meta_pela_metade(void);
void t_sem_meta_o_diretorio_nao_existe(void);
void t_versao_desconhecida_e_ignorada(void);
void t_listagem_do_cartao_distingue_vazio_de_falha(void);
void t_meta_ilegivel_aparece_com_defeito(void);

void t_largura_soma_avancos_nao_tinta(void);
void t_largura_bate_com_o_que_desenha(void);
void t_acento_nao_gasta_linha_a_mais(void);
void t_glifo_faltante_conta_em_vez_de_sumir(void);
void t_o_texto_do_sistema_nao_tem_faltante(void);
void t_acento_e_um_glifo_nao_dois_bytes(void);
void t_orcamento_de_28_colunas(void);
void t_truncar_conta_bytes_de_caractere_inteiro(void);
void t_paragrafo_quebra_na_palavra(void);
void t_negativo_inverte_e_volta(void);

void t_agenda_mostra_o_proximo(void);
void t_sem_compromisso_a_agenda_nao_desenha_nada(void);
void t_o_trabalho_vem_agrupado_pela_lista(void);
void t_tarefa_sem_lista_ainda_tem_grupo(void);
void t_lista_sem_tarefa_no_aparelho_nao_vira_cabecalho(void);
void t_dia_cheio_corta_com_mais(void);
void t_atrasada_sobe_e_feita_fica_no_lugar(void);
void t_atrasada_e_selo_nao_bloco(void);
void t_filete_marca_o_que_veio_de_fora(void);
void t_o_convite_some_depois_dos_primeiros_dias(void);
void t_anotacao_nao_entra_no_trabalho(void);
void t_rodape_segue_o_cursor(void);
void t_repouso_nao_tem_cursor(void);
void t_dia_vazio_nao_quebra(void);
void t_a_home_diz_quando_ha_coisa_esperando_rede(void);
void t_a_home_avisa_o_limite_sem_assustar(void);

void t_renomear_limpa_o_que_quebraria_o_perfil(void);
void t_o_nome_trocado_aqui_sobe_e_e_confirmado(void);
void t_o_nome_trocado_no_aplicativo_chega_ao_aparelho(void);
void t_nome_novo_depois_de_formatar_nao_perde_para_o_antigo(void);
void t_servidor_sem_nome_recebe_o_do_aparelho(void);

void t_duas_anotacoes_no_mesmo_dia_sao_duas(void);
void t_abrir_a_anotacao_mostra_o_que_foi_dito(void);
void t_a_lista_de_anotacoes_pagina_e_abre(void);
void t_confirmar_uma_anotacao_abre_o_pronto(void);
void t_anotou_sem_tipo_vira_anotacao_e_nao_sobe(void);

int main(void)
{
    printf("\n\033[1mTinto — o aparelho no PC\033[0m\n\n");

    t_liga_e_desenha();
    t_evento_de_dia_inteiro_aparece_e_vem_primeiro();
    t_o_dia_inteiro_fica_na_agenda();
    t_a_tarefa_feita_se_prende_ao_dia();
    t_o_item_guarda_fim_local_e_dia_inteiro();
    t_a_faixa_de_horario();
    t_paragrafo_cortado_diz_que_foi_cortado();
    t_a_reticencia_cabe_dentro_da_largura();
    t_a_proposta_nao_toca_no_cartao();
    t_confirmar_grava_e_enfileira();
    t_confirmar_apaga_o_audio_e_guarda_a_transcricao();
    t_anotacao_confirmada_nao_entra_na_fila();
    t_a_frase_longa_chega_inteira_ao_conferir();
    t_evento_do_google_e_so_leitura();
    t_evento_nao_oferece_marcar_feita();
    t_quando_oferece_os_dias_prontos();
    t_hora_e_de_evento_prazo_e_de_tarefa();
    t_as_telas_de_quando_cabem_no_quadro();
    t_o_hibrido_vale_em_todo_lugar();
    t_tirar_a_data_e_so_de_tarefa();
    t_anotacao_nao_vai_pro_google();
    t_tres_eventos();
    t_cursor_nao_passa_do_topo();
    t_a_carga_atualiza_a_topbar_por_faixa();
    t_cursor_para_na_ultima_linha();
    t_menu_abre_e_fecha_a_gaveta();
    t_esquerda_nao_volta();
    t_back_fecha_a_gaveta_antes_de_voltar();
    t_gaveta_e_submenu_da_pagina();
    t_o_menu_abre_as_acoes_do_item();
    t_item_ilegivel_aparece_na_agenda();
    t_o_dia_do_calendario_lista_tarefas_como_a_agenda();
    t_tarefa_concluida_mora_no_dia_da_conclusao();
    t_as_telas_de_tarefa_leem_a_mesma_fonte();
    t_o_navegador_de_dia_mostra_que_esta_em_foco();
    t_confirmar_guarda_o_que_a_tela_de_resultado_vai_listar();
    t_conferir_tem_o_kicker_e_o_cartao_de_tres_linhas();
    t_captura_e_apagada_no_dia_em_que_nasceu();
    t_confirmar_duas_vezes_nao_manda_duas_vezes();
    t_coluna_do_campo_nao_encosta_no_valor();
    t_o_valor_do_campo_nao_perde_dado_para_a_enfase();
    t_o_detalhe_rola_quando_nao_cabe();
    t_a_raiz_de_ajustes_sao_cinco_destinos();
    t_minha_conta_tem_quatro_estados();
    t_minha_conta_reconhece_wifi_sem_internet();
    t_minha_conta_nao_rola_em_nenhum_estado();
    t_o_proprietario_se_troca_em_qualquer_estado();
    t_sincronizacao_mostra_o_card_e_as_agendas();
    t_doze_agendas_paginam_e_as_de_fora_sao_ditas();
    t_buscando_agendas_e_o_mesmo_card_com_pontinhos();
    t_aparencia_no_desenho_da_fase_3();
    t_som_no_desenho_da_fase_3();
    t_armazenamento_no_desenho_da_fase_3();
    t_sobre_no_desenho_da_fase_3();
    t_restaurar_diz_o_que_sai_e_o_que_fica();
    t_preparando_mostra_as_etapas();
    t_restaurar_usa_a_confirmacao_do_sistema();
    t_o_sobre_tem_porta_no_armazenamento();
    t_a_capa_diz_o_que_vem();
    t_a_hora_se_corrige_sozinha_com_rede();
    t_a_conclusao_mostra_as_tres_verificacoes();
    t_a_rolagem_anda_de_pagina_inteira();
    t_virar_pagina_chega_ao_vidro_como_tela_nova();
    t_mover_o_cursor_nunca_paga_refresh_completo();
    t_o_pull_de_fundo_nao_anima_a_barra();
    t_o_back_diz_para_onde_volta();
    t_o_desenho_nao_espera_a_fila_esvaziar();
    t_tres_acoes_de_uma_fala_sobem_todas();
    t_o_resultado_so_entra_quando_a_fila_esvazia();
    t_a_fala_nao_espera_a_rede_voltar();
    t_o_servidor_so_pode_ser_https();
    t_o_contrato_cabe_nos_buffers_do_device();
    t_voltar_da_rede_continua_pelo_delta();
    t_eventos_wifi_seguidos_nao_reiniciam_o_ntp();
    t_sem_rede_nao_se_grava();
    t_rede_que_cai_no_meio_da_fala_descarta_o_audio();
    t_rede_que_cai_estruturando_descarta_na_hora();
    t_rede_que_cai_no_conferir_descarta_a_proposta();
    t_a_paginacao_conta_as_paginas_num_lugar_so();
    t_os_menus_paginam_em_vez_de_deslizar();
    t_a_legenda_pesa_na_conta_da_pagina();
    t_a_pagina_diz_onde_acaba_e_nao_so_onde_comeca();
    t_a_tela_bloqueada_no_desenho_da_fase_3();
    t_a_tela_bloqueada_diz_dia_livre();
    t_bloqueio_mostra_so_hoje_pelo_nome();
    t_o_contador_de_pagina_mostra_a_direcao();
    t_o_rodape_anima_a_espera();
    t_o_detalhe_nao_corta_o_titulo();
    t_o_dia_pagina_quando_tem_coisa_demais();
    t_o_cartao_e_varrido_uma_vez_por_quadro();
    t_montar_duas_vezes_le_o_cartao_uma_vez();
    t_nenhum_compromisso_do_dia_fica_de_fora();
    t_conexao_conectada_mostra_o_card_e_as_acoes();
    t_conexao_sem_rede_salva_nao_oferece_esquecer();
    t_o_sinal_do_wifi_nao_congela_na_conexao();
    t_a_oscilacao_do_sinal_nao_gasta_tinta();
    t_a_senha_do_wifi_nao_mora_no_cartao();
    t_o_cartao_velho_migra_a_senha_e_se_limpa();
    t_a_lista_de_redes_poe_o_que_se_sabe_na_legenda();
    t_a_busca_de_redes_anima_os_pontinhos();
    t_senha_recusada_e_sem_resposta_sao_telas_diferentes();
    t_senha_recusada_nao_fica_tentando_sozinha();
    t_conectando_anima_os_pontinhos();
    t_esquecer_rede_pergunta_antes();
    t_lista_de_redes_vazia_explica_e_oferece_saida();
    t_a_tela_de_senha_diz_a_rede_e_conta_os_caracteres();
    t_sincronizacao_separa_os_dois_erros();
    t_marca_de_tarefa_sai_do_prazo();
    t_a_tira_do_calendario_nao_sobrepoe();
    t_a_contagem_da_tira_conta_o_que_o_dia_mostra();
    t_o_calendario_mostra_a_concluida_no_dia_da_conclusao();
    t_a_linha_da_tira_nao_chama_feita_de_por_fazer();
    t_back_segurado_volta_pra_home();
    t_cartao_le_o_que_escreveu();
    t_docar_chega_no_estado();
    t_pinagem_final_dos_botoes();

    printf("\n  \033[2m— o e-ink físico —\033[0m\n");
    t_uc8253_inicia_com_a_configuracao_do_painel();
    t_uc8253_gira_o_framebuffer_para_o_gabinete();
    t_uc8253_primeiro_quadro_faz_refresh_completo();
    t_uc8253_o_plano_velho_e_escrito_depois_do_refresh();
    t_uc8253_dois_quadros_deixam_a_referencia_em_dia();
    t_uc8253_parcial_entra_no_modo_parcial();
    t_uc8253_parcial_usa_a_waveform_de_fabrica();
    t_uc8253_parcial_desfaz_a_temperatura_forcada();
    t_uc8253_parcial_separa_as_tres_operacoes();
    t_uc8253_a_faxina_leva_o_vidro_aos_extremos();
    t_uc8253_a_faxina_nao_finge_temperatura();
    t_uc8253_o_completo_tambem_usa_a_waveform_nativa();
    t_uc8253_nao_desliga_o_painel_entre_dois_quadros();
    t_uc8253_desliga_manda_power_off();
    t_uc8253_faixa_pinta_so_a_faixa();
    t_tick_com_a_tela_parada_nao_pede_quadro();
    t_tick_que_vira_o_minuto_pede_quadro();
    t_tick_gravando_pede_quadro();
    t_gesto_sem_rede_acontece_e_espera_na_fila();
    t_mudar_a_data_pela_mao();
    t_escolher_no_mes_tem_rota_propria();
    t_a_confirmacao_volta_para_onde_a_pessoa_estava();
    t_o_mostrador_marca_qualquer_hora();
    t_tarefa_com_hora_vive_na_regua_e_se_marca();
    t_motor_a_mesma_tela_e_um_quadro_so();
    t_motor_tela_sem_cursor_nao_paga_o_segundo_quadro();
    t_motor_tela_com_cursor_pinta_o_seletor_depois();
    t_motor_abrir_caixa_limpa_o_chao_antes();
    t_motor_fechar_caixa_e_um_quadro_so();
    t_motor_trocar_de_tela_com_caixa_nao_soma_os_dois_rituais();
    t_motor_nunca_devolve_plano_vazio();
    t_refresco_quadro_que_muda_muito_pede_completo();
    t_eink_sair_do_teclado_repinta_inteiro();

    printf("\n  \033[2m— a memória interna —\033[0m\n");
    t_memoria_distingue_ausencia_de_filesystem();
    t_memoria_distingue_diretorio_vazio_de_falha();
    t_memoria_informa_tipo_do_caminho();
    t_memoria_injeta_falha_ao_criar_diretorio();
    t_memoria_lista_diretorio_vazio_criado();
    t_memoria_nao_confunde_prefixo_com_diretorio_pai();
    t_memoria_cheia_e_observavel_e_apagar_recupera();
    t_memoria_cheia_ou_somente_leitura_continua_legivel();
    t_arvore_ausente_e_virgem();
    t_arvore_sem_formato_e_danificada();
    t_arvore_com_raiz_de_arquivo_e_danificada();
    t_arvore_de_versao_futura_nao_e_tocada();
    t_arvore_sem_uma_pasta_e_parcial();
    t_prepara_nao_toca_no_que_esta_fora_da_raiz();
    t_prepara_propaga_falha_de_cada_operacao();
    t_formato_anterior_sobrevive_ao_rename_falho();
    t_prova_de_escrita_nao_deixa_residuo();
    t_prova_de_escrita_limpa_residuo_do_boot_anterior();
    t_prova_de_escrita_denuncia_memoria_travada();
    t_arvore_vazia_e_virgem_e_nao_reparo();
    t_arvore_com_arquivo_alheio_continua_danificada();
    t_perfil_ausente_nao_e_formato_invalido();
    t_perfil_grava_e_rele_o_schema_exato();
    t_perfil_nao_regenera_id_de_cartao_que_ja_tem_dono();
    t_perfil_id_tem_32_hex();
    t_perfil_trunca_nome_sem_partir_utf8();
    t_perfil_rename_falho_nao_deixa_perfil_pela_metade();
    t_gravar_item_cria_as_pastas_do_caminho();
    t_memoria_virgem_vai_para_boas_vindas();
    t_o_voltar_anda_para_tras_no_trecho();
    t_voltar_da_conclusao_nao_abre_data_e_hora_vazia();
    t_pular_o_wifi_e_voltar_reabre_o_wifi();
    t_voltar_para_o_wifi_conectado_e_seguir_volta_a_conta();
    t_voltar_para_a_conta_ja_vinculada_diz_conectada();
    t_a_primeira_etapa_nao_tem_para_onde_voltar();
    t_o_diagnostico_de_midia_nao_volta();
    t_o_voltar_so_anda_dentro_do_primeiro_uso();
    t_o_relogio_anda_fora_da_home();
    t_o_minuto_pede_quadro_o_segundo_nao();
    t_cada_defeito_da_midia_tem_fase_propria();
    t_formato_futuro_nao_oferece_reparo();
    t_arvore_danificada_vai_para_reparo();
    t_antes_da_home_nenhum_botao_escapa();
    t_boas_vindas_abre_o_nome();
    t_reboot_retoma_na_primeira_pendencia();
    t_desligar_sem_nome_volta_para_as_boas_vindas();
    t_onboarding_concluido_abre_a_home();
    t_formatar_faz_o_radio_esquecer_a_rede();
    t_caixa_alta_redesenha_na_hora();
    t_power_no_primeiro_uso_trava_e_destrava();
    t_restaurar_reinicia_o_chip();
    t_back_da_conexao_no_primeiro_uso_diz_voltar();
    t_primeiro_uso_escuta_o_relogio_e_se_apresenta();
    t_conta_sem_resposta_tem_saida();
    t_wifi_no_primeiro_uso_pede_a_hora();
    t_primeiro_uso_se_reapresenta_sozinho();
    t_fluxo_do_primeiro_uso_de_ponta_a_ponta();
    t_reiniciar_religa_a_rede_e_nao_pede_a_hora();
    t_a_conclusao_diz_o_que_ficou_faltando();
    t_aparelho_configurado_nao_repete_o_primeiro_uso();
    t_reparo_nao_destrutivo_nao_apaga_nada();
    t_formatar_exige_dois_gestos_e_a_pergunta_nasce_no_nao();
    t_so_o_sim_deliberado_formata();
    t_voltar_da_confirmacao_nao_apaga();
    t_ausencia_e_comunicacao_nunca_oferecem_formatar();
    t_a_tela_de_preparacao_aparece_antes_de_formatar();
    t_logo_vem_do_asset_oficial();
    t_cartao_removido_em_uso_cai_na_tela_de_memoria();
    t_gravacao_nao_continua_sem_onde_escrever();
    t_mutacoes_respeitam_estado_da_memoria();

    printf("\n  \033[2m— datas, json e cartão —\033[0m\n");
    t_data_ida_e_volta();
    t_data_atravessa_o_mes();
    t_dia_da_semana();
    t_json_le_o_contrato();
    t_json_nao_confunde_chave_com_valor();
    t_json_trunca_em_vez_de_rejeitar();
    t_cartao_grava_e_le_igual();
    t_cartao_tres_dias_doze_itens();
    t_corte_de_energia_nao_deixa_meta_pela_metade();
    t_sem_meta_o_diretorio_nao_existe();
    t_versao_desconhecida_e_ignorada();
    t_listagem_do_cartao_distingue_vazio_de_falha();
    t_meta_ilegivel_aparece_com_defeito();

    printf("\n  \033[2m— a tinta —\033[0m\n");
    t_largura_soma_avancos_nao_tinta();
    t_largura_bate_com_o_que_desenha();
    t_acento_nao_gasta_linha_a_mais();
    t_glifo_faltante_conta_em_vez_de_sumir();
    t_o_texto_do_sistema_nao_tem_faltante();
    t_acento_e_um_glifo_nao_dois_bytes();
    t_orcamento_de_28_colunas();
    t_truncar_conta_bytes_de_caractere_inteiro();
    t_paragrafo_quebra_na_palavra();
    t_negativo_inverte_e_volta();

    printf("\n  \033[2m— a home em duas zonas —\033[0m\n");
    t_agenda_mostra_o_proximo();
    t_sem_compromisso_a_agenda_nao_desenha_nada();
    t_o_trabalho_vem_agrupado_pela_lista();
    t_tarefa_sem_lista_ainda_tem_grupo();
    t_lista_sem_tarefa_no_aparelho_nao_vira_cabecalho();
    t_dia_cheio_corta_com_mais();
    t_atrasada_sobe_e_feita_fica_no_lugar();
    t_atrasada_e_selo_nao_bloco();
    t_filete_marca_o_que_veio_de_fora();
    t_o_convite_some_depois_dos_primeiros_dias();
    t_anotacao_nao_entra_no_trabalho();
    t_rodape_segue_o_cursor();
    t_repouso_nao_tem_cursor();
    t_dia_vazio_nao_quebra();
    t_a_home_diz_quando_ha_coisa_esperando_rede();
    t_a_home_avisa_o_limite_sem_assustar();

    printf("\n  \033[2m— os casos de uso —\033[0m\n");
    t_marcar_feita_sem_rede_enfileira();
    t_desmarcar_enfileira_o_estado_novo();
    t_cartao_falhou_entao_nada_aconteceu();
    t_a_acao_carrega_o_horario_do_gesto();
    t_marcar_cinco_vezes_e_um_estado();
    t_marca_item_de_outro_dia_no_lugar_certo();
    t_renomear_trava_o_titulo();
    t_renomear_trunca_em_vez_de_recusar();
    t_apagar_some_do_cartao_e_engole_a_fila();
    t_tarefa_com_hora_continua_tarefa();
    t_mudar_a_data_nao_move_o_item_de_pasta();
    t_mudar_a_hora_leva_o_fim_junto();
    t_a_conversao_olha_o_cartao_nao_o_cache();
    t_dado_todo_ajuste_tem_chave_no_config();
    t_ajuste_grava_e_sobrevive_ao_reboot();
    t_ajuste_apara_em_vez_de_recusar();
    t_ajuste_igual_nao_escreve_de_novo();
    t_config_de_versao_antiga_usa_o_padrao();
    t_sem_cartao_o_aparelho_diz_e_nao_finge();
    t_cartao_virgem_nao_bloqueia();
    t_marcar_derruba_todos_os_caches();
    t_falha_de_listagem_chega_ao_estado_do_app();
    t_tarefa_futura_de_outro_dia_aparece_hoje();
    t_dia_passado_nao_recebe_pendencia();
    t_o_calendario_marca_o_mes_inteiro();
    t_o_calendario_ve_alem_da_primeira_pagina();
    t_evento_de_varios_dias_ocupa_todos_eles();
    t_descartar_invalida_o_cache();
    t_item_que_nao_cabe_e_contado();
    t_ir_para_dia_troca_e_invalida();

    printf("\n  \033[2m— a nota —\033[0m\n");
    t_conteudo_nao_vira_tofu();
    t_texto_de_excecao_nao_vira_tofu();
    t_a_fonte_enorme_da_conta_do_cartaz();
    t_a_citacao_e_mesmo_diferente_do_corpo();
    t_a_serifa_editorial_e_mesmo_outra_fonte();
    t_a_marca_dagua_e_tinta_cheia();
    t_a_transcricao_crua_aparece_sempre();
    t_a_origem_do_item_nao_se_sincroniza();
    t_concluir_mora_no_detalhe_da_tarefa();
    t_o_detalhe_diz_quando_a_tarefa_foi_concluida();
    t_o_detalhe_separa_data_e_prazo_da_tarefa();
    t_o_evento_diz_em_qual_agenda_mora();
    t_o_detalhe_quebra_o_valor_em_vez_de_cortar();
    t_apagar_alcanca_o_que_veio_do_google();
    t_um_so_detalhe_para_todo_tipo();
    t_o_detalhe_da_tarefa_responde();
    t_a_fala_original_desce_no_proprio_item();
    t_desmarcar_nao_abre_a_fala();
    t_abrir_tarefa_pela_lista_abre_a_tarefa_certa();
    t_o_gesto_em_voo_aparece_na_barra();
    t_destravar_devolve_a_tela_em_que_estava();
    t_fala_original_mostra_o_item_e_a_gravacao_inteira();
    t_anotacao_diz_que_e_so_no_aparelho();
    t_sem_ia_a_nota_abre_do_mesmo_jeito();
    t_sem_nem_transcricao_o_aviso_muda();
    t_a_duracao_sai_em_minutos_e_segundos();
    t_anotacoes_lista_por_recencia_agrupada_por_dia();
    t_anotacoes_vazia_convida_em_vez_de_calar();
    t_a_transcricao_vem_da_nota_e_nao_do_item();
    t_item_do_google_nao_tem_nota_nenhuma();

    printf("\n  \033[2m— o aparelho navega —\033[0m\n");
    t_ok_marca_a_tarefa_do_cursor();
    t_a_home_redesenha_com_o_cartao_novo();
    t_direita_entra_no_item_e_back_volta();
    t_direita_dentro_do_item_nao_empilha();
    t_travado_nao_anda();

    printf("\n  \033[2m— a voz, offline —\033[0m\n");
    t_voz_bloqueada_pede_desbloqueio();
    t_sem_minutos_recusa_e_leva_a_voz();
    t_conta_caida_manda_reconectar_e_nao_esperar();
    t_google_revogado_mantem_conta_e_pede_novo_login();
    t_o_aviso_de_reconectar_nao_insiste();
    t_hal_sem_microfone_nao_derruba_o_aparelho();
    t_falar_pausar_retomar_e_confirmar();
    t_o_gesto_fisico_da_voz_respeita_o_modo_escolhido();
    t_a_transcricao_corre_como_fifo();
    t_capturar_nao_pergunta_nada();
    t_grava_de_qualquer_tela();
    t_sem_rede_o_botao_de_voz_recusa_na_hora();
    t_com_a_rede_de_volta_o_mesmo_botao_grava();
    t_a_voz_devolve_a_tela_de_onde_se_falou();
    t_o_resultado_so_aparece_depois_da_resposta();
    t_back_segurado_encerra_a_volta_da_voz();
    t_descartar_pergunta_com_o_nao_selecionado();
    t_descartar_confirmado_nao_deixa_rastro();
    t_pausado_o_medidor_zera_mas_a_tela_fica();
    t_o_log_registra_duracao_e_nunca_conteudo();
    t_depois_do_ok_a_faixa_estrutura_e_o_aparelho_trava();
    t_a_resposta_fecha_a_faixa_e_abre_o_recibo();
    t_sem_resposta_a_faixa_destrava_e_diz_onde_a_fala_esta();
    t_envio_que_nao_saiu_descarta_e_diz_a_verdade();
    t_estruturando_diz_e_pisca();
    t_gravar_que_nao_comeca_diz_por_que();
    t_conferir_so_sai_decidindo();
    t_o_id_da_fala_e_o_do_comeco();
    t_nenhuma_falha_deixa_gravacao_no_cartao();
    t_prazo_da_tela_e_maior_que_o_da_conexao();
    t_o_panico_funciona_durante_a_estruturacao();
    t_a_faixa_sem_resposta_sai_com_qualquer_botao();
    t_pausar_nao_gasta_whisper();
    t_o_id_com_dois_pontos_grava_e_volta_inteiro();
    t_o_que_a_fala_criou_mora_no_dia_do_evento();
    t_confirmar_apaga_a_captura_crua();
    t_descartar_apaga_mesmo_a_gravacao();
    t_tarefa_sem_data_continua_no_dia_da_fala();
    t_o_gesto_troca_o_id_provisorio_pelo_do_google();
    t_uma_fala_com_tres_acoes_nao_duplica_nenhuma();
    t_gesto_de_edicao_nao_mexe_no_id();
    t_o_pull_derruba_as_marcas_do_calendario();
    t_e2e_a_serie_diaria_chega_ao_mes_inteiro();
    t_o_lote_em_pedacos_nao_repinta_a_cada_pedaco();
    t_lote_que_termina_vazio_ainda_rele_a_tela();
    t_e2e_a_rotina_marca_o_mes_com_uma_linha();
    t_o_dia_distante_e_consulta_e_nao_vai_para_o_cartao();
    t_a_consulta_do_dia_sobrevive_ao_recarregamento();
    t_o_mes_pedido_sai_uma_vez_e_morre_na_resposta();
    t_o_item_do_dia_consultado_abre_e_marca();
    t_e2e_abrir_um_dia_passado_pede_e_mostra();
    t_apagado_no_google_some_de_qualquer_dia();
    t_a_tarefa_apagada_no_google_some_da_tela();
    t_o_cursor_nao_passa_por_cima_de_um_lote_que_falhou();
    t_o_cursor_avanca_quando_o_lote_grava();
    t_sincronizar_nao_apaga_a_fala_que_originou_o_item();
    t_desconectar_preserva_e_outra_conta_limpa();
    t_voltar_do_calendario_devolve_a_home_de_hoje();
    t_dia_futuro_vazio_nao_anuncia_secao();
    t_dia_futuro_com_compromisso_diz_quando();

    printf("\n  \033[2m— a fala do mês —\033[0m\n");
    t_a_fala_do_mes_mostra_o_numero_e_o_que_sobra();
    t_esgotado_mostra_zero();
    t_o_numero_grande_cabe_e_so_tem_digitos();
    t_sem_conta_a_fala_do_mes_nao_inventa_numero();
    t_ajustes_abre_a_fala_do_mes();
    t_armazenamento_sai_em_gb_com_uma_casa();
    t_cartao_quase_vazio_sai_em_mb();
    t_espaco_desconhecido_nao_vira_zero();

    printf("\n  \033[2m— os invariantes de tela —\033[0m\n");
    t_grid_as_zonas_cobrem_a_tela_sem_encostar();
    t_grid_a_largura_util_fecha_com_a_margem();
    t_grid_a_faixa_e_um_retangulo_so();
    t_refresco_o_foco_e_parcial_mesmo_medindo_muito();
    t_refresco_mover_o_foco_na_home_declara_a_intencao();
    t_a_agenda_anuncia_a_saida_no_rodape();
    t_a_gaveta_fecha_em_vez_de_voltar();
    t_a_agenda_leva_o_dia_no_cabecalho();
    t_o_cabecalho_segue_o_dia_visto();
    t_o_local_aparece_em_qualquer_evento();
    t_o_cabecalho_do_dia_nao_encavala();
    t_o_calendario_tem_a_moldura_da_agenda();
    t_o_resumo_do_calendario_conta_em_palavras();
    t_o_dia_vazio_nao_promete_a_semana();
    t_o_hud_distingue_subir_de_descer_de_falhar();
    t_chrome_a_barra_nao_e_uma_faixa_preta();
    t_chrome_a_barra_continua_dizendo_as_coisas();
    t_chrome_o_rodape_e_claro_quando_nada_acontece();
    t_chrome_nenhuma_tela_assenta_o_proprio_seletor();
    t_chrome_o_evento_em_foco_inverte_so_o_conteudo();
    t_chrome_o_canto_nao_danca_com_o_sync();
    t_chrome_muitas_tarefas_nao_quebram_a_tela();

    t_lancador_o_aparelho_liga_na_home();
    t_o_cabecalho_diz_o_nome_e_nao_o_email();
    t_lancador_o_ok_abre_a_agenda();
    t_lancador_entrar_na_agenda_pede_o_delta();
    t_lancador_o_back_na_home_nao_cria_tela();
    t_lancador_a_grade_anda_em_duas_dimensoes();
    t_lancador_cada_cartao_abre_a_sua_area();
    t_lancador_voltar_devolve_o_cartao_de_onde_se_saiu();
    t_lancador_o_menu_nao_abre_gaveta_na_home();
    t_lancador_a_vista_monta_os_quatro_cartoes();
    t_lancador_a_vista_leva_o_foco_do_estado();
    t_lancador_a_saudacao_segue_a_hora();
    t_lancador_sem_hora_a_saudacao_nao_inventa();
    t_lancador_o_rodape_nao_promete_back();
    t_lancador_a_barra_mostra_a_data();
    t_lancador_o_foco_preenche_o_cartao();
    t_lancador_mover_o_foco_troca_o_bloco_preto();
    t_lancador_a_grade_cabe_sem_invadir_a_moldura();
    t_lancador_cada_cartao_desenha_icone_e_textos();
    t_lancador_o_texto_do_cartao_cabe_no_cartao();
    t_lancador_o_completo_nao_assenta_o_cartao_em_foco();
    t_lancador_entrar_em_ajustes_mede_a_memoria();
    t_lancador_a_agenda_anda_um_dia_para_cada_lado();
    t_lancador_voltar_para_a_agenda_devolve_hoje();
    t_lancador_as_tarefas_nao_mudam_com_o_dia();
    t_lancador_um_dia_sem_pasta_nao_herda_o_dia_anterior();
    t_lancador_a_contagem_regressiva_so_existe_hoje();
    t_lancador_a_agenda_nao_abre_o_detalhe_do_dia();

    t_grid_icone_de_lista_cabe_na_linha();
    t_acervo_guarda_os_tres_estados();
    t_acervo_vista_continuar_lendo_e_a_ultima_aberta();
    t_acervo_ui_cabe_no_quadro();
    t_acervo_ui_cabecalhos_tem_icones_legiveis();
    t_acervo_ui_miniatura_nao_cobre_biblioteca();
    t_obra_ui_sinopse_longa_rola_sem_ser_cortada();
    t_contrato_o_lote_do_backend_e_lido_inteiro();
    t_contrato_o_lote_vazio_nao_e_erro();
    t_contrato_o_id_volta_igual_do_cartao();
    t_contrato_o_tamanho_do_lote_confere_a_copia();
    t_acervo_navega_a_home_abre_o_acervo();
    t_acervo_navega_ao_entrar_pede_o_catalogo_online();
    t_acervo_navega_a_gaveta_e_do_acervo();
    t_acervo_navega_o_ok_abre_o_que_esta_aqui();
    t_acervo_navega_a_obra_remota_comeca_a_baixar();
    t_acervo_navega_mantem_a_obra_do_cursor_visivel();
    t_acervo_navega_as_setas_viram_pagina();
    t_acervo_navega_o_livro_devolve_a_memoria();
    t_acervo_a_capa_desce_depois_do_texto();
    t_leitor_pagina_sem_cortar_palavra();
    t_leitor_nao_corta_caractere_utf8();
    t_leitor_trocar_a_fonte_preserva_a_posicao();
    t_leitor_a_letra_maior_pagina_menos();
    t_leitor_voltar_devolve_a_mesma_pagina();
    t_leitor_o_fim_nao_passa_do_fim();
    t_leitor_a_ultima_pagina_nunca_vira_branco();
    t_leitor_a_porcentagem_vem_do_offset();
    t_leitor_reabre_onde_parou();
    t_leitor_a_pagina_cabe_na_tela();
    t_leitor_conta_as_paginas_da_obra();
    t_leitor_usa_flash_na_capa_e_parcial_entre_textos();
    t_leitor_menu_tem_alinhamento();
    t_acervo_navega_continuar_lendo_e_um_foco_real();
    t_acervo_navega_continuar_lembra_a_ultima_do_mesmo_dia();
    t_acervo_ui_a_linha_tem_area_propria();
    t_acervo_ui_o_vazio_aparece_escrito();
    t_acervo_ui_o_vazio_mostra_um_livro();
    t_acervo_ui_o_titulo_do_vazio_e_centrado();
    t_acervo_ui_o_vazio_mostra_o_qr_do_aplicativo();
    t_acervo_vista_a_legenda_muda_com_o_progresso();
    t_acervo_vista_o_icone_diz_o_que_o_OK_faz();
    t_acervo_vista_vazio_explica();
    t_acervo_vista_filtra_sem_perder_o_resto();
    t_acervo_o_lote_do_servidor_vira_obra_no_cartao();
    t_acervo_catalogo_igual_nao_regrava_o_cartao();
    t_acervo_obra_removida_online_continua_local();
    t_acervo_obra_apenas_online_some_com_o_catalogo();
    t_acervo_percorre_todos_os_lotes_antes_de_remover();
    t_acervo_o_texto_so_vira_obra_se_chegar_inteiro();
    t_acervo_baixa_em_blocos_sem_prender_a_navegacao();
    t_acervo_retoma_o_part_depois_de_reiniciar();
    t_acervo_reiniciar_retomara_depois_de_confirmar_catalogo();
    t_acervo_sync_nao_pisca_o_estado_online();
    t_acervo_cartao_cheio_nao_comeca_download();
    t_acervo_o_part_sobrevive_ao_reboot_sem_virar_obra();
    t_acervo_a_rede_cair_no_meio_nao_deixa_obra_falsa();
    t_acervo_erro_do_servidor_solta_a_obra_na_hora();
    t_acervo_separa_transferencia_de_leitura();
    t_acervo_lista_da_mais_recente_para_a_mais_antiga();
    t_acervo_ignora_o_que_esta_pela_metade();
    t_acervo_remove_so_a_copia_local();
    t_acervo_descarta_local_sem_apagar_a_origem_online();
    t_acervo_o_clique_marca_baixando_na_mesma_hora();
    t_mapa_a_sentinela_alcanca_a_ultima_tela();
    t_mapa_toda_tela_esta_declarada();
    t_mapa_tela_de_leitura_nao_pinta_seletor();
    t_grid_a_barra_ocupa_a_mesma_altura_em_toda_tela();
    t_grid_o_canto_de_estado_e_identico_entre_telas();
    t_grid_nenhuma_tela_pede_glifo_que_nao_existe();
    t_grid_trocar_de_tela_nao_deixa_resto();
    t_grid_sair_do_teclado_nao_deixa_o_teclado();
    t_grid_fechar_a_faixa_devolve_a_tela_inteira();

    printf("\n  \033[2m— a faixa ancorada —\033[0m\n");
    t_faixa_limpa_o_chao_antes_de_escrever();
    t_faixa_nao_escreve_fora_do_retangulo();
    t_faixa_nunca_cobre_a_barra_nem_o_topo_do_miolo();
    t_faixa_negativa_inverte_a_faixa_inteira();
    t_faixa_os_tres_usos_dividem_a_mesma_geometria();
    t_faixa_botao_comprido_trunca_dentro_da_faixa();
    t_faixa_a_gaveta_nao_vaza_por_cima_do_conteudo();
    t_faixa_na_gaveta_o_texto_cede_espaco_ao_valor();
    t_faixa_o_conteudo_nao_encosta_nos_botoes();
    t_o_aparelho_mede_a_memoria_ao_ligar();
    t_o_rotulo_nao_invade_a_coluna_do_valor();
    t_o_sobre_diz_de_quem_e_o_aparelho();
    t_o_botao_de_voz_alterna_na_propria_linha();

    printf("\n  \033[2m— a conectividade —\033[0m\n");
    t_a_lista_de_redes_diz_forca_e_quais_estao_salvas();
    t_rede_aberta_conecta_sem_pedir_senha();
    t_o_hud_diz_quando_o_aparelho_esta_esperando();
    t_esquecer_a_rede_apaga_a_senha_e_desconecta();
    t_o_cursor_pula_as_linhas_que_so_informam();
    t_esquecer_cabe_inteiro_na_linha();
    t_procurando_diz_que_esta_procurando();
    t_entrar_no_wifi_manda_procurar();
    t_escolher_uma_rede_nova_pede_a_senha();
    t_rede_oculta_pede_o_nome_e_depois_a_senha();
    t_a_rede_conectada_fica_guardada();
    t_sem_rede_guardada_o_boot_segue();
    t_a_lista_marca_a_rede_conhecida();
    t_o_indice_responde_sem_tocar_o_cartao();
    t_o_indice_anda_com_a_escrita();
    t_a_poda_mantem_o_cartao_do_tamanho_da_janela();
    t_as_marcas_do_mes_vem_do_servidor();
    t_apagar_nao_deixa_pasta_para_tras();
    t_rotina_todo_dia();
    t_rotina_dias_da_semana();
    t_rotina_mes_e_ano();
    t_rotina_acaba_e_tem_buraco();
    t_rotina_sem_regra_e_regra_estranha();
    t_rotina_em_palavras();
    t_o_contrato_le_um_evento();
    t_o_contrato_sabe_o_que_se_repete();
    t_o_cursor_nao_atravessa_o_fim_do_array();
    t_dia_inteiro_vence_a_hora();
    t_a_tarefa_traz_data_e_estado();
    t_item_sem_id_nao_entra();
    t_o_pull_percorre_a_lista_inteira();
    t_o_pull_grava_no_cartao_e_derruba_o_cache();
    t_o_primeiro_boot_registra_o_aparelho();
    t_o_token_fica_no_cofre_e_vale_no_boot_seguinte();
    t_o_cartao_nao_guarda_mais_prova_nem_token();
    t_o_cartao_velho_migra_prova_e_token();
    t_a_prova_nao_muda_entre_boots();
    t_ao_ligar_ele_descobre_o_dono_e_puxa_o_dia();
    t_desvincular_avisa_o_servidor_antes_de_esquecer();
    t_restaurar_desvincula_antes_de_formatar();
    t_evento_falado_sobrevive_ao_reinicio();
    t_boot_sem_hora_nao_poda_o_cartao();
    t_tarefa_com_hora_falada_sobrevive_ao_reinicio();
    t_o_gesto_carrega_o_id_da_operacao();
    t_o_pull_traz_o_fuso_da_conta();
    t_a_captura_volta_com_as_acoes_propostas();
    t_captura_sem_acao_ainda_traz_a_frase();
    t_o_gesto_sobe_um_por_vez();
    t_o_gesto_nao_espera_o_pull_pendurado();
    t_da_fala_ate_a_home_mudar();
    t_renomear_e_apagar_sobem_pro_google();
    t_apagar_offline_e_o_pull_nao_ressuscita();
    t_gesto_recusado_avisa_no_vidro();
    t_gesto_antigo_pede_a_verdade_inteira_do_google();
    t_a_captura_espera_a_linha_vagar();
    t_a_voz_apaga_o_que_ja_existe();
    t_a_voz_edita_sem_duplicar();
    t_a_fila_sobrevive_ao_boot();
    t_anotacao_nao_vira_gesto_no_google();
    t_descartar_a_proposta_nao_sobe_nada();
    t_o_codigo_de_pareamento_chega_do_servidor();
    t_sem_rede_nao_se_tenta_sincronizar();
    t_nunca_falou_diz_nunca();
    t_o_armazenamento_diz_o_que_ocupa();
    t_cartao_quase_cheio_avisa_sem_apagar_nada();
    t_armazenamento_sem_medida_nao_inventa();
    t_entrar_no_armazenamento_mede_o_cartao();
    t_apagar_pergunta_antes_e_nasce_no_nao();
    t_desistir_de_apagar_volta_pra_vida_normal();
    t_so_o_sim_deliberado_apaga();
    t_sem_rede_a_conexao_manda_ligar_o_wifi();
    t_com_rede_e_sem_conta_a_tela_espera_o_codigo();
    t_pareado_a_tela_diz_a_conta_e_a_fila();
    t_conta_conectada_da_acesso_ao_aplicativo();
    t_ajustes_abre_minha_conta();
    t_vincular_espera_o_codigo_em_vez_de_inventar();
    t_vincular_manda_logar_antes_de_digitar();
    t_desconectar_nasce_no_nao_e_diz_o_que_fica();
    t_o_primeiro_uso_diz_que_esta_conectando_antes_da_conta();
    t_as_fases_de_rede_e_conta_desenham_alguma_coisa();
    t_a_lista_traz_quantos_tem_e_quantos_foram();
    t_o_item_diz_de_que_fala_ele_veio();
    t_com_ntp_e_conta_nada_no_relogio_se_ajusta_a_mao();
    t_o_cartao_vazio_pede_a_colheita_inteira();
    t_cada_rota_sai_com_o_metodo_que_o_servidor_espera();
    t_cadastrado_no_painel_o_codigo_aparece_sozinho();
    t_o_codigo_nao_e_pedido_com_a_tela_fechada();
    t_o_aparelho_nao_fala_https_antes_de_saber_a_hora();
    t_token_recusado_faz_o_aparelho_se_registrar_de_novo();
    t_a_prova_que_sobe_e_a_que_fica_no_cofre_sao_a_mesma();
    t_o_tinto_sem_token_tenta_de_novo_ate_se_registrar();
    t_as_agendas_chegam_e_enchem_a_tela();
    t_a_busca_de_agendas_espera_a_vez_em_vez_de_sumir();
    t_a_busca_de_agendas_desiste_e_oferece_tentar_de_novo();
    t_a_busca_de_agendas_anima_os_pontinhos();
    t_o_gesto_nao_atropela_o_pull_em_voo();
    t_a_linha_da_nuvem_se_solta_sozinha();
    t_marcar_agenda_espera_a_vez_em_vez_de_sumir();
    t_o_interruptor_vira_quando_o_servidor_confirma();
    t_o_interruptor_avisa_que_esta_indo_antes_de_virar();
    t_desligar_uma_agenda_apaga_o_que_ela_ja_tinha_trazido();
    t_um_pull_comum_nao_apaga_nada();
    t_grid_nenhum_rotulo_e_cortado_no_meio_de_um_caractere();
    t_o_paragrafo_obedece_a_quebra_de_linha();
    t_a_home_vazia_diz_que_esta_vazia();
    t_a_marca_dagua_e_mais_clara_que_a_tinta_cheia();
    t_o_dia_vazio_usa_a_mesma_marca_dagua();
    t_o_dia_tem_duas_secoes_e_nenhuma_e_captura();
    t_o_dia_lista_em_ordem_crescente_de_horario();
    t_a_gravacao_nao_entra_na_regua_do_dia();
    t_item_sem_titulo_nunca_aparece_em_branco();
    t_tarefa_aparece_da_data_ate_o_prazo();
    t_tarefa_com_hora_nao_vira_atrasada();
    t_o_calendario_tem_uma_legenda_so_e_e_a_do_google();
    t_a_tira_mostra_o_que_o_dia_sob_o_cursor_tem();
    t_o_mes_vazio_diz_o_nome_do_mes();
    t_a_tira_acompanha_o_cursor_na_grade();
    t_andar_um_dia_na_grade_le_o_dia_e_mais_nada();
    t_todo_estado_do_vinculo_diz_alguma_coisa();
    t_as_recusas_do_gesto_dizem_o_remedio_certo();
    t_o_cursor_pula_as_linhas_que_nao_se_apertam();
    t_do_repouso_ate_o_qr_sem_perder_nenhum_gesto();
    t_pilha_cheia_troca_o_topo_em_vez_de_sumir();
    t_sincronizacao_sem_conta_explica_em_vez_de_ficar_vazia();
    t_sincronizacao_lista_agendas_e_o_que_esta_ligado();
    t_a_hora_pela_internet_desliga_o_ajuste_a_mao();
    t_a_hora_de_12_horas_diz_am_e_pm();
    t_a_hora_do_item_tambem_obedece_ao_ajuste();
    t_a_barra_segue_o_ajuste_de_hora();
    t_o_campo_de_hora_segue_o_formato_escolhido();
    t_desligada_a_rede_os_campos_ficam_editaveis();
    t_ajustar_a_hora_a_mao_muda_o_relogio_do_aparelho();
    t_o_ajuste_a_mao_parte_da_hora_atual_e_usa_os_dois_eixos();
    t_o_dia_respeita_o_tamanho_do_mes();
    t_sem_hora_valida_os_campos_comecam_numa_data_sensata();
    t_no_primeiro_uso_o_direcional_escolhe_o_campo();
    t_ok_no_fuso_nao_grava_o_relogio();
    t_sem_tocar_em_nada_a_tela_trava_sozinha();
    t_bloqueio_automatico_pode_ser_desligado();
    t_gravando_a_tela_nao_trava_por_tempo();
    t_no_primeiro_uso_a_tela_nao_trava_por_tempo();
    t_o_interruptor_da_hora_pela_rede_liga_e_desliga();
    t_ligar_a_hora_pela_rede_pergunta_na_hora();
    t_o_fuso_se_ajusta_e_vale_com_o_ntp_ligado();


    t_xadrez_posicao_inicial();
    t_xadrez_peao_anda_sem_saltar();
    t_xadrez_lance_troca_o_turno();
    t_xadrez_en_passant();
    t_xadrez_roque_move_rei_e_torre();
    t_xadrez_promocao_oferece_quatro_pecas();
    t_xadrez_reconhece_mate_e_empates();
    t_xadrez_navega_so_por_candidatos_validos();
    t_xadrez_maquina_e_legal_deterministica_e_fatiada();
    t_xadrez_maquina_media_aproveita_captura_livre();
    t_xadrez_maquina_facil_nao_desfaz_o_ultimo_lance();
    t_xadrez_salva_e_retoma_lance();
    t_xadrez_recusa_salvamento_corrompido();
    t_xadrez_pasta_ausente_e_partida_ausente();
    t_xadrez_historico_vem_recente_e_opcoes_nao_duplicam_lance();
    t_xadrez_da_home_ao_primeiro_lance_local();
    t_xadrez_saida_preserva_ou_abandona_partida();
    t_xadrez_salvamento_corrompido_tem_saida_segura();
    t_xadrez_back_limpa_ao_trocar_tabuleiro_e_saida();
    t_xadrez_back_segurado_volta_para_home();
    t_xadrez_maquina_responde_e_salva_sem_bloquear_back();
    t_xadrez_maquina_com_pretas_da_pessoa_joga_primeiro();
    t_xadrez_maquina_dificil_nao_espera_dezenas_de_voltas();
    t_xadrez_continuar_so_aparece_com_salvamento_valido();
    t_xadrez_ui_desenha_tabuleiro_e_pecas();
    t_xadrez_cancelar_promocao_nao_sai_da_partida();
    t_xadrez_ui_promocao_nao_mostra_texto_atras();
    t_xadrez_ui_centraliza_e_gira_peca_local();
    t_xadrez_ui_dama_tem_cinco_pontas_e_base_nitida();
    t_xadrez_ui_cheia_e_vazada_usam_a_mesma_silhueta();
    t_xadrez_v3_opcoes_menu_giro_e_historico();
    t_xadrez_v3_confirma_empate_e_abandono();
    t_xadrez_v3_mate_mostra_tabuleiro_antes_do_resultado();
    t_xadrez_ui_v3_desenha_opcoes_gaveta_e_resultado();
    t_xadrez_ui_v3_horizontal_usa_o_vidro_deitado();
    t_xadrez_v3_direcional_acompanha_horizontal_e_giro();
    t_xadrez_ui_historico_descreve_os_lances();
    t_xadrez_ui_icones_dizem_qual_acao_e_peca();
    t_xadrez_ui_capa_guia_a_escolha_da_partida();
    t_xadrez_ui_acoes_e_placar_sao_legiveis();
    t_xadrez_ajuda_e_ultima_jogada();
    t_xadrez_gaveta_alterna_ajuda_sem_trocar_tela();
    t_xadrez_revanche_repete_opcoes_e_troca_as_cores();
    t_renomear_limpa_o_que_quebraria_o_perfil();
    t_o_nome_trocado_aqui_sobe_e_e_confirmado();
    t_o_nome_trocado_no_aplicativo_chega_ao_aparelho();
    t_nome_novo_depois_de_formatar_nao_perde_para_o_antigo();
    t_servidor_sem_nome_recebe_o_do_aparelho();
    t_duas_anotacoes_no_mesmo_dia_sao_duas();
    t_abrir_a_anotacao_mostra_o_que_foi_dito();
    t_a_lista_de_anotacoes_pagina_e_abre();
    t_confirmar_uma_anotacao_abre_o_pronto();
    t_anotou_sem_tipo_vira_anotacao_e_nao_sobe();

    printf("\n  %d testes, \033[%sm%d falhas\033[0m\n\n",
           teste_total, teste_falhas ? "31" : "32", teste_falhas);
    return teste_falhas ? 1 : 0;
}
